## Semana 02 Estruturas de dados 
#### Prof. Ricardo S Oliveira 
##### Disciplina: Informática Aplicada 
##### Data: 14/03/2026 Versão : inical

### 2.0 Arrays 
##### Arrays e matrizes são estruturas de dados fundamentais para a manipulação de conjuntos de dados em programação.

In [118]:
numeros = [1,2,3,4,5] 

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [119]:
frutas =["apple","banana","mango"]

3-element Vector{String}:
 "apple"
 "banana"
 "mango"

### 2.1 Vetores
#####  Um vetor é um array de 1 dimensão. Ele pode ser criado através da declaração do nome do vetor e atribuindo uma lista de valores entre colchetes, separados por espaço, por vírgula ou por ponto-e-vírgula, como mostram os exemplos a seguir:

In [1]:
a = [2 3 7]

1×3 Matrix{Int64}:
 2  3  7

In [2]:
a = [3,4,7]

3-element Vector{Int64}:
 3
 4
 7

In [3]:
a = [3;4;7]

3-element Vector{Int64}:
 3
 4
 7

In [4]:
a = [2 3 7]
a'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 2
 3
 7

In [5]:
(a')'

1×3 Matrix{Int64}:
 2  3  7

In [9]:
a[1],a[3]

(2, 7)

In [10]:
a[0]

BoundsError: BoundsError: attempt to access 1×3 Matrix{Int64} at index [0]

In [11]:
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [12]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [13]:
rand(3)

3-element Vector{Float64}:
 0.877395976094113
 0.8898541847809842
 0.7589180175428921

In [14]:
rand(3)

3-element Vector{Float64}:
 0.9301153374261641
 0.9886899913433149
 0.6414755085552053

In [102]:
v = range(0, stop=1,length=5)

0.0:0.25:1.0

In [106]:
# Operacções com vetores em Julia
x = [4,5,8]; 
y = [1, 2, 3];

In [ ]:

length(x) # tamanho do vetor 

3

In [ ]:
println(x+y) # adicao de vetores 

[5, 7, 11]


In [ ]:
println(x.+y) # multiplicacao elmento por elemento

[5, 7, 11]


In [126]:
println(x .*y)

[4, 10, 24]


In [115]:
println(x.^2)

[16, 25, 64]


#### 2.2 Matrizes
##### Outra estrutura de dados importante é a definição de matrizes, que são arrays multidimensionais.

In [22]:
A = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [23]:
A[1,3]

3

In [26]:
A[1,3]=13

13

In [27]:
A

3×3 Matrix{Int64}:
 1  2  13
 4  5   6
 7  8   9

In [28]:
A = ones(3,2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [29]:
A = zeros(3,2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [30]:
A = rand(3,2)

3×2 Matrix{Float64}:
 0.0118722  0.959737
 0.395627   0.147969
 0.800061   0.791097

In [31]:
A = rand(3,2)

3×2 Matrix{Float64}:
 0.774343  0.865825
 0.798298  0.182297
 0.720347  0.877833

In [32]:
fill(2,3)

3-element Vector{Int64}:
 2
 2
 2

In [33]:
fill(23,3,2)

3×2 Matrix{Int64}:
 23  23
 23  23
 23  23

In [40]:
# transposta 
A'

2×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.774343  0.798298  0.720347
 0.865825  0.182297  0.877833

In [44]:
A = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [46]:
size(A)

(3, 3)

In [59]:
length(A)

MethodError: MethodError: no method matching length(::typeof(push!))
The function `length` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  length(!Matched::BitSet)
   @ Base bitset.jl:355
  length(!Matched::VSCodeServer.JSON.Parser.MemoryParserState)
   @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.189.2/scripts/packages/JSON/src/Parser.jl:29
  length(!Matched::Compiler.InstructionStream)
   @ Base ../usr/share/julia/Compiler/src/ssair/ir.jl:275
  ...


In [95]:
v= [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [97]:
push!(v)=4
v

3-element Vector{Int64}:
 1
 2
 3

In [98]:
length(v)

3

In [99]:
Base.pop!(v)

3

In [100]:
v

2-element Vector{Int64}:
 1
 2

In [133]:
append!(v,[2])

MethodError: MethodError: no method matching resize!(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ::Int64)
The function `resize!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  resize!(!Matched::Compiler.IncrementalCompact, ::Int64)
   @ Base ../usr/share/julia/Compiler/src/ssair/ir.jl:1739
  resize!(!Matched::Compiler.InstructionStream, ::Any)
   @ Base ../usr/share/julia/Compiler/src/ssair/ir.jl:291
  resize!(!Matched::VSCodeServer.JSON.Parser.PushVector, ::Integer)
   @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.189.2/scripts/packages/JSON/src/pushvector.jl:29
  ...


In [154]:

A = [1 2 3; 4 5 6; 7 8 10];

In [155]:
A[1:2,:] # selecionando as 2 primeiras linhas e todas colunas

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [156]:
A[:,1:2] # selecionando as 2 primeiras colunas e todas  as linhas 

3×2 Matrix{Int64}:
 1  2
 4  5
 7  8

In [157]:
using LinearAlgebra

In [158]:
transpose(A) # transposta da matriz 

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4   7
 2  5   8
 3  6  10

In [159]:
det(A) # determinante da matriz 

-3.0

In [160]:
eigvals(A) # autovalores da matriz 

3-element Vector{Float64}:
 -0.9057401795217577
  0.1982468633970094
 16.707493316124747

In [161]:
inv(A) # inversa da matriz 

3×3 Matrix{Float64}:
 -0.666667  -1.33333   1.0
 -0.666667   3.66667  -2.0
  1.0       -2.0       1.0

#### 2.3 Dicionários 
##### Em Julia, devido a sua essência em computação científica, essas estruturas são ainda mais importantes e eficientes.

In [36]:
D= Dict("banana" => "amarelo", "melancia" => "verde")

Dict{String, String} with 2 entries:
  "melancia" => "verde"
  "banana"   => "amarelo"

In [37]:
D["banana"]

"amarelo"

In [38]:
collect(values(D))

2-element Vector{String}:
 "verde"
 "amarelo"

In [120]:
collect(keys(D))

2-element Vector{String}:
 "melancia"
 "banana"

In [125]:
# Criando dicionarios
teacher = Dict("name"=>"Sabrina", "age"=>32, "class"=>"math")

Dict{String, Any} with 3 entries:
  "name"  => "Sabrina"
  "class" => "math"
  "age"   => 32

In [130]:
# acessando e atualizando 
teacher["class"]= "linear programming"
teacher

Dict{String, Any} with 3 entries:
  "name"  => "Sabrina"
  "class" => "linear programming"
  "age"   => 32

In [131]:
teacher["major"]="Computer Science"

"Computer Science"

In [132]:
teacher

Dict{String, Any} with 4 entries:
  "name"  => "Sabrina"
  "major" => "Computer Science"
  "class" => "linear programming"
  "age"   => 32